MODEL_HYPERPARAMETERS_2H = {
    "num_epochs": 200,
    "batch_size": 256,
    "batches_per_epoch": 300,
    "learning_rate": 0.001,
    "context_length" : 70,
                "numerical_features": [
                                    'c', 'h', 'l','v','close_diff','close_diff56','std_volatility_4_42_diff',
                                    'bb_spread', 'bb_trend','sma_14_trend', 'sma_56_trend', 'pct_16T_high', 'pct_96T_high', 
                                    'cycle_z_scores','daily_cycle_strength', 'weekly_cycle_strength','range_volatility_detail_1_anomaly',
                                    'std_volatility_detail_1_anomaly','range_volatility_detail_1_to_4_ratio',
                                    'std_volatility_detail_1_to_4_ratio','vti_trend','symbol_vti_diff','vti_corr_56'
                                    ],
    "categorical_features": ['hour','dow','year','bb_category','symbol_encoded',
                            'downside_threshold_prediction'
                            ],
    "categorical_cardinalities": [7,5,10,3,22,2],
    "evaluation_columns": ['c'],
    "prediction_horizon": 4,
    "attention_heads": 8,
    "hidden_state_dim": 32,
    "feedforward_dim": 32,
    "dropout": 0.05,
    "transformer_layers": 2,
    "individual": True,
    "patch_len": 32,
    "stride": 16,
    "padding_patch": 'end',
    "revin": False,
    "affine": False,
    "patience": 25,
    "kernel_size": 25,
    "subtract_last": 0,
    "scaling_method": "rolling",
    "optimizer": "adam",
    "categorical": True,
    "decomposition": True,
    "data_window_length": 3,
    "categorical_embedding_dim": 64,
    "mode": "max_estimation",
    "partial_epochs": 10,
    "partial_lr": 0.001,
    "partial_batches_per_epoch": 20,
    "partial_batch_size": 128,
}

MODEL_HYPERPARAMETERS_3D = {'num_epochs': 200, 
                            'batch_size': 256, 
                            'batches_per_epoch': 300, 
                            'learning_rate': 0.001, 
                            'context_length': 240, 
                            'numerical_features': [
                                        'c', 'h', 'l', 'v', 'close_diff', 'close_diff56', 'std_volatility_4_42_diff', 'bb_spread', 'bb_trend', 'sma_14_trend', 'sma_56_trend', 'pct_16T_high',
                                        'pct_96T_high', 'cycle_z_scores', 'daily_cycle_strength', 'weekly_cycle_strength', 'range_volatility_detail_1_anomaly', 'std_volatility_detail_1_anomaly', 
                                        'range_volatility_detail_1_to_4_ratio', 'std_volatility_detail_1_to_4_ratio', 'vti_trend', 'symbol_vti_diff', 'vti_corr_56'],
                            "categorical_features": [
                                'hour','dow','year','bb_category','symbol_encoded',
                                'downside_threshold_prediction',
                            ],
                             "categorical_cardinalities": [7,5,10,3,22,2],
                            'evaluation_columns': ['c'], 
                            'prediction_horizon': 42, 
                            'attention_heads': 4, 
                            'hidden_state_dim': 64, 
                            'feedforward_dim': 64, 
                            'dropout': 0.1, 
                            'transformer_layers': 2, 
                            'individual': True, 
                            'patch_len': 16, 
                            'stride': 4, 
                            'padding_patch': 'end', 
                            'revin': False, 
                            'affine': False, 
                            'patience': 25, 
                            'kernel_size': 25, 
                            'subtract_last': 0, 
                            'scaling_method': 'rolling', 
                            'optimizer': 'adam', 
                            'categorical': True, 
                            'decomposition': False, 
                            'data_window_length': 2, 
                            'categorical_embedding_dim': 32, 
                            'mode': 'max_estimation', 
                            'partial_epochs': 10, 
                            'partial_lr': 0.001, 
                            'partial_batches_per_epoch': 20, 
                            'partial_batch_size': 128}